Runner.create!([
  {first_name: "Donia", last_name: "Costanza", username: "dcostanza", password_digest: "$2a$10$54mu8Cp3rbjHFGb8eabAQeoKeNvHrwVsM.q0fko2MTyq4UHy3fAoq", email: nil, image_url: nil, city: nil, bio: nil},
  {first_name: "Michaeline", last_name: "Avrashin", username: "mavrashin", password_digest: "$2a$10$xzZi9HtQ3wfkSMNzo/C.ZewaUP98N1NyPj99GqEllsQwm5RxWdfHm", email: nil, image_url: nil, city: nil, bio: nil},
  {first_name: "John", last_name: "Bramhill", username: "jbramhill", password_digest: "$2a$10$p5uDo4a40Ms9IgDFpQGq5u5UN6cjqiq23BkL7Zfx5cBzV6rYI4GQi", email: nil, image_url: nil, city: nil, bio: nil},
  {first_name: "Caroline", last_name: "Folder", username: "cfolder", password_digest: "$2a$10$qLEVHe1xmWiip6f4OvFug.z9Q48XqywMmA0obeSOjKaf2tnVYWFXa", email: nil, image_url: nil, city: nil, bio: nil},
  {first_name: "Clevie", last_name: "Kennett", username: "ckennett", password_digest: "$2a$10$tRIOmiyM4gfCIMqrai/2YO9Yoip4i2HDotdsWfSp3oNRnTJYJuRya", email: nil, image_url: nil, city: nil, bio: nil},
  {first_name: "Emory", last_name: "Seagood", username: "eseagood", password_digest: "$2a$10$iavW5qdKIW2LHfeDe0KSsO0b./s5bejxA70jfg8t0NkPtGWX/Vw6G", email: nil, image_url: nil, city: nil, bio: nil},
  {first_name: "Noelle", last_name: "Dizlie", username: "ndizlie", password_digest: "$2a$10$NfKhD8hJdIteImM4NKql1ugSUcg5aakZJCjKOHJtL.K3msS6Db4du", email: nil, image_url: nil, city: nil, bio: nil},
  {first_name: "Sloane", last_name: "Brute", username: "sbrute", password_digest: "$2a$10$OAj8VX49qSN5cckbrolPeOknK02R5CkIu4BsUd8tGVL.rw6cH29em", email: nil, image_url: nil, city: nil, bio: nil},
  {first_name: "Winny", last_name: "Smiley", username: "wsmiley", password_digest: "$2a$10$gTFDYmrWKrHT3oxgiGFDDuecASjrhXbYGx3mcFqLm.VmYGy6Icm6i", email: nil, image_url: nil, city: nil, bio: nil},
  {first_name: "Ruggiero", last_name: "Slowly", username: "rslowly", password_digest: "$2a$10$pdfYQdnPmC16eLw1.IKtnO.4rBUi3rnJPeUlZ5NDnL5SIbAzSNihG", email: nil, image_url: nil, city: nil, bio: nil},
  {first_name: "Filia", last_name: "Al Hirsi", username: "fal hirsi", password_digest: "$2a$10$K7ZeyCMsBqs0nDNmpBhUk.wBzstLgEKAeYLilGiPI9qjS4EHN0spC", email: nil, image_url: nil, city: nil, bio: nil},
  {first_name: "Hadria", last_name: "Lutzmann", username: "hlutzmann", password_digest: "$2a$10$IpTYZWVfWBb/WUM1z7EZOuDoezDyRHARJN2INkkCVcwbzGqtBuHyi", email: nil, image_url: nil, city: nil, bio: nil},
  {first_name: "Michail", last_name: "Wolfit", username: "mwolfit", password_digest: "$2a$10$7BV5OlrATmTAUm/7hbkE8eqoVjh9m7WlsJwCCsInZffcz4Wt00HAe", email: nil, image_url: nil, city: nil, bio: nil},
  {first_name: "Shirlee", last_name: "Sidlow", username: "ssidlow", password_digest: "$2a$10$UOoepqTvsQEfa7TZ3HE41esr1hPFAusPpELAhsxVaH7jHk/GGj4dS", email: nil, image_url: nil, city: nil, bio: nil},
  {first_name: "Lib", last_name: "Haddrell", username: "lhaddrell", password_digest: "$2a$10$g/KtjUjp9PLdTjT6n4JoTOH6BEg/qBHrhrmJh7UWyGdtUsi2IZeyG", email: nil, image_url: nil, city: nil, bio: nil},
  {first_name: "Clarence", last_name: "Edmonstone", username: "cedmonstone", password_digest: "$2a$10$mPH1/3aoGqj/p0JyGIVf7OuPY1P8sWz6OBnRd3Bb2I1N009Nz9ue2", email: nil, image_url: nil, city: nil, bio: nil},
  {first_name: "Carolan", last_name: "Carress", username: "ccarress", password_digest: "$2a$10$x1nxin6iFt5AEAa2vAHv.uhMrrraeOejzVJoPGvTWe2XqZv61DANe", email: nil, image_url: nil, city: nil, bio: nil},
  {first_name: "Diannne", last_name: "Izzatt", username: "dizzatt", password_digest: "$2a$10$5LjyuERkvUxo7QLt4HYo1eLXbUDSMTY2Eqk/KlksMzMsJIffOy5VS", email: nil, image_url: nil, city: nil, bio: nil},
  {first_name: "Abrahan", last_name: "Dearnaly", username: "adearnaly", password_digest: "$2a$10$vB9hP4eF3yrau/FH0woZ.e4r6Tob8H2h5ZwecPfQKaEwfOD6WUyIC", email: nil, image_url: nil, city: nil, bio: nil},
  {first_name: "Man", last_name: "Knotton", username: "mknotton", password_digest: "$2a$10$xO0mWUl0wBAY2mk3ZCx.3.qpAXvl2xirL0map5tkyvxIGRXS3j9XS", email: nil, image_url: nil, city: nil, bio: nil},
  {first_name: "Akmal", last_name: "Khadir", username: "akmalkhadir", password_digest: "$2a$10$5RjdLBinzqjz7nOJCKh8teAhnVUMYIP7J0OElY.eGzx5SsRwUwbiC", email: "akmal.khadir@yahoo.com", image_url: "https://akmalkhadir.com/wp-content/uploads/2019/01/akmal_profile.jpg", city: "London, UK", bio: "Everyday I run, run, run till I turn yellow,\ncause you ain’t a runner if you’re \nnot yellow."}
])

Run.create!([
  {name: "New Year's Run", description: "Kick start your new year by clocking some miles. We will start at Victoria Gate, Hyde Park and finishes at Hyde Park Corner after 2 loops.", start_location: "Victoria Gate, Hyde Park", end_location: "Hyde Park Corner", date: "2018-05-03 10:00:00", distance: 10.0, is_private: false, runner_id: 21, start_lat: nil, start_lng: nil, end_lat: nil, end_lng: nil},
  {name: "Where's Wally? fun run!", description: "Walk, jog or run your way around Clapham Common and help give vital literacy skills to disadvantaged kids in the UK.", start_location: "Clapham Common, London", end_location: "Very Common, London", date: "2018-12-19 12:45:00", distance: 5.0, is_private: false, runner_id: 1, start_lat: nil, start_lng: nil, end_lat: nil, end_lng: nil},
  {name: "Forrest Gump", description: "Run Forrest, run!", start_location: "Epping Forest, London", end_location: "Waltham Forest, London", date: "2018-12-22 08:00:00", distance: 10.0, is_private: true, runner_id: 1, start_lat: nil, start_lng: nil, end_lat: nil, end_lng: nil},
  {name: "Run With Ducks", description: "You, me & ducks. We run!", start_location: "Round Pond, Hyde Park", end_location: "Buckingham Palace", date: "2018-12-20 08:00:00", distance: 5.0, is_private: false, runner_id: 1, start_lat: nil, start_lng: nil, end_lat: nil, end_lng: nil},
  {name: "FutureRun", description: "Run in the Future", start_location: "Now", end_location: "The Future", date: "2018-12-21 09:45:00", distance: 21.0, is_private: false, runner_id: 3, start_lat: nil, start_lng: nil, end_lat: nil, end_lng: nil},
  {name: "Hello Run", description: "Run and say hello", start_location: "Hello", end_location: "Bye", date: "2018-12-21 15:00:00", distance: 5.0, is_private: false, runner_id: 3, start_lat: nil, start_lng: nil, end_lat: nil, end_lng: nil},
  {name: "Boxing Day Run", description: "Run while boxing.", start_location: "Oxford Circus Underground Station", end_location: "Tottenham Hale Retail Park", date: "2018-12-26 22:00:12", distance: 10.0, is_private: false, runner_id: 3, start_lat: nil, start_lng: nil, end_lat: nil, end_lng: nil},
  {name: "Powerpuff Run", description: "Fighting crimes trying to save the world, we run just in time!", start_location: "London Eye", end_location: "Tower of London", date: "2018-12-27 08:30:00", distance: 10.0, is_private: false, runner_id: 3, start_lat: nil, start_lng: nil, end_lat: nil, end_lng: nil},
  {name: "Run Run Run", description: "Run Run Run and Run and Run till you're tired.", start_location: "Forest", end_location: "Beach", date: "2018-12-27 18:00:00", distance: 40.0, is_private: false, runner_id: 3, start_lat: nil, start_lng: nil, end_lat: nil, end_lng: nil},
  {name: "Hello", description: "Hello Run", start_location: "Hello", end_location: "Bye", date: "2018-12-27 12:00:00", distance: 6.0, is_private: false, runner_id: 3, start_lat: nil, start_lng: nil, end_lat: nil, end_lng: nil},
  {name: "Hello", description: "Hello no 2", start_location: "Nowhere", end_location: "Somewhere", date: "2018-12-28 20:17:00", distance: 90.0, is_private: false, runner_id: 3, start_lat: nil, start_lng: nil, end_lat: nil, end_lng: nil},
  {name: "Hello3", description: "Hello Hello Hello", start_location: "Hello form the other side", end_location: "This side.", date: "2018-12-29 18:00:00", distance: 10.0, is_private: false, runner_id: 3, start_lat: nil, start_lng: nil, end_lat: nil, end_lng: nil},
  {name: "Hello4", description: "hELLO hELLO Hello Hello", start_location: "Underworld", end_location: "Waterworld", date: "2018-12-26 20:22:11", distance: 80.0, is_private: false, runner_id: 3, start_lat: nil, start_lng: nil, end_lat: nil, end_lng: nil},
  {name: "Walthamstow Wetlands Morning Run", description: "Easy morning run around Walthamstow Wetlands. All abilities are welcomed", start_location: "Ferry Lane Entrance, Walthamstow Wetlands", end_location: "The Engine Room Cafe", date: "2019-01-15 08:30:48", distance: 5.0, is_private: false, runner_id: 21, start_lat: "51.586803", start_lng: "-0.053563", end_lat: "51.585548", end_lng: "-0.054473"},
  {name: "Mornington Chasers Regents's Park", description: "This is the last race in this popular 6 race series run on the first Sunday in the month over the winter months. Regent's Park is the perfect setting for a flat, fast and traffic-free Sunday morning 10k. The course consists of an accurately measured 3 lap route within the iconic Regents Park and is chip timed. The race attracts runners of all abilities and beginners are most welcome.\n\nThis March why not go mad and run our 10K in fancy dress? We'd like as many fancy dress runners as possible. If you are already planning a spring marathon dressed up as a Brussels sprout, or know someone else who is, our March 10K is the perfect race to try out that crazy costume.", start_location: "The Hub, Regent's Park", end_location: "The Hub, Regent's Park", date: "2018-02-01 08:30:45", distance: 10.0, is_private: true, runner_id: 21, start_lat: "51.532562", start_lng: "-0.160071", end_lat: "51.532562", end_lng: "-0.160071"},
  {name: "London Easter 10k", description: "Now firmly established on the capital's race calendar, the London Easter 10K returns for a sixth year to the splendid surroundings of Regent's Park. The race features chip timing and prizes will be awarded to the leading runners and age category winners. Finish line goodies and a bespoke medal will be on offer for every finisher, plus there will be Easter eggs and other seasonal goodies to all finishers.", start_location: "The Hub, Regent's Park", end_location: "The Hub, Regent's Park", date: "2018-03-06 09:30:42", distance: 10.0, is_private: false, runner_id: 21, start_lat: "51.532562", start_lng: "-0.160071", end_lat: "51.532562", end_lng: "-0.160071"},
  {name: "Back to the Future Run", description: "Where's Marty?", start_location: "Big Ben", end_location: "The Future", date: "2019-10-25 07:00:00", distance: 10.0, is_private: false, runner_id: 3, start_lat: "51.500733", start_lng: "-0.126814", end_lat: "51.521278", end_lng: "-0.079097"},
  {name: "Valentine's Day Run", description: "Run with cupids!", start_location: "Valentines Park", end_location: "Valentines Park", date: "2019-02-14 16:59:00", distance: 5.0, is_private: false, runner_id: 3, start_lat: "51.563853", start_lng: "0.06678", end_lat: "51.573658", end_lng: "0.066181"},
  {name: "MSF Run", description: "Raise money for international aid!", start_location: "Clapham Junction", end_location: "Elephant & Castle", date: "2019-01-24 22:00:00", distance: 10.0, is_private: false, runner_id: 3, start_lat: "51.464434", start_lng: "-0.172121", end_lat: "51.464486", end_lng: "-0.204952"},
  {name: "Ketchup Run", description: "Run while eating chips with ketchup", start_location: "KFC", end_location: "McDonald's", date: "2018-12-30 12:45:00", distance: 8.0, is_private: false, runner_id: 3, start_lat: "51.561987", start_lng: "-0.033388", end_lat: "51.52981", end_lng: "-0.096978"},
  {name: "Yellow Run", description: "Run till you're yellow", start_location: "Yellow Brick Road", end_location: "Red Brick Road", date: "2018-12-30 20:10:00", distance: 7.0, is_private: false, runner_id: 3, start_lat: "51.504128", start_lng: "-0.081874", end_lat: "51.523852", end_lng: "-0.101536"},
  {name: "KFC Run", description: "Fried chicken yo!", start_location: "KFC", end_location: "Sam's Chicken", date: "2018-12-31 12:00:00", distance: 5.0, is_private: false, runner_id: 3, start_lat: "51.561987", start_lng: "-0.021894", end_lat: "51.606984", end_lng: "-0.070432"},
  {name: "Deer Run", description: "Running like Bambi", start_location: "Walthamstow", end_location: "Leyton", date: "2019-01-01 17:00:00", distance: 5.0, is_private: false, runner_id: 3, start_lat: "51.58693", start_lng: "-0.033388", end_lat: "51.561961", end_lng: "-0.021894"},
  {name: "Just A Run", description: "Run, duh!", start_location: "Liverpool Street", end_location: "Your Street", date: "2019-01-02 12:00:00", distance: 10.0, is_private: false, runner_id: 3, start_lat: "51.518755", start_lng: "-0.083626", end_lat: "51.519289", end_lng: "-0.089441"},
  {name: "Happy Run", description: "Run like happy chickens!", start_location: "Nando's, Westbourne Grove, Bayswater, London", end_location: "Nando's, High Street, Walthamstow, London", date: "2018-12-31 09:10:00", distance: 15.0, is_private: true, runner_id: 3, start_lat: "51.515494", start_lng: "-0.191073", end_lat: "51.584912", end_lng: "-0.02266"},
  {name: "Regent’s Park Summer 10K – September", description: "Final race of this six race series, run totally within the Park - an outstanding location within the heart of London, mainly flat with slight undulations. Races will be the first Sunday in each month, April to September. All abilities welcome.", start_location: "Regent's Gate", end_location: "Regent's Park", date: "2019-09-04 11:35:19", distance: 10.0, is_private: false, runner_id: 21, start_lat: "51.542319", start_lng: "-0.155771", end_lat: "51.531271", end_lng: "-0.156969"},
  {name: "The Big Half", description: "Created by London Marathon Events Ltd, in partnership with Sported, The Big Half is a new one-day festival centred around the half marathon distance, which aims to be truly global and uniquely local in a celebration of the wonderful cultural diversity of the great city of London.", start_location: "Tower Bridge", end_location: "Greenwich", date: "2018-12-10 12:30:15", distance: 21.6, is_private: false, runner_id: 21, start_lat: "51.505499", start_lng: "-0.075358", end_lat: "51.482085", end_lng: "-0.004542"},
  {name: "London Landmarks Half Marathon", description: "Back for it's second year, the London Landmarks Half Marathon is a closed road, flat, central London run and is the only half marathon to go through both the City of London and City of Westminster.\n\nThe event is not your average half marathon! From cultural landmarks and heritage to the city's quirky and hidden secrets, runners get to explore the capital on a route like no other!", start_location: "Pall Mall", end_location: "Downing Street", date: "2019-03-24 09:30:00", distance: 21.6, is_private: false, runner_id: 21, start_lat: "51.507197", start_lng: "-0.132344", end_lat: "51.503167", end_lng: "-0.126211"},
  {name: "Peckham 10K", description: "Hello runners it is coming around to the time of the 10k run in Peckham\n\nThe route is 1600m + 3laps. On race completion you will be awarded a medal and t-shirt to show off to all your friends! There will also be trophies for the top three male and female runners!", start_location: "Peckham Rye Common", end_location: "Peckham Rye Park", date: "2019-01-14 04:56:26", distance: 10.0, is_private: false, runner_id: 21, start_lat: "51.461439", start_lng: "-0.065028", end_lat: "51.456463", end_lng: "-0.06007"}
])

RunnersRun.create!([
  {runner_id: 2, run_id: 1},
  {runner_id: 3, run_id: 1},
  {runner_id: 4, run_id: 1},
  {runner_id: 5, run_id: 1},
  {runner_id: 6, run_id: 1},
  {runner_id: 7, run_id: 1},
  {runner_id: 7, run_id: 2},
  {runner_id: 2, run_id: 2},
  {runner_id: 4, run_id: 2},
  {runner_id: 5, run_id: 2},
  {runner_id: 6, run_id: 2},
  {runner_id: 20, run_id: 8},
  {runner_id: 19, run_id: 8},
  {runner_id: 18, run_id: 8},
  {runner_id: 17, run_id: 8},
  {runner_id: 16, run_id: 8},
  {runner_id: 15, run_id: 8},
  {runner_id: 14, run_id: 8},
  {runner_id: 13, run_id: 8},
  {runner_id: 8, run_id: 3},
  {runner_id: 9, run_id: 3},
  {runner_id: 10, run_id: 3},
  {runner_id: 11, run_id: 3},
  {runner_id: 12, run_id: 3},
  {runner_id: 14, run_id: 3},
  {runner_id: 15, run_id: 3},
  {runner_id: 16, run_id: 3},
  {runner_id: 16, run_id: 4},
  {runner_id: 17, run_id: 4},
  {runner_id: 18, run_id: 4},
  {runner_id: 19, run_id: 4},
  {runner_id: 20, run_id: 4},
  {runner_id: 1, run_id: 4},
  {runner_id: 1, run_id: 2},
  {runner_id: 1, run_id: 3},
  {runner_id: 1, run_id: 5},
  {runner_id: 1, run_id: 6},
  {runner_id: 1, run_id: 7},
  {runner_id: 3, run_id: 4},
  {runner_id: 1, run_id: 27},
  {runner_id: 1, run_id: 29},
  {runner_id: 1, run_id: 20},
  {runner_id: 3, run_id: 2},
  {runner_id: 3, run_id: 28},
  {runner_id: 3, run_id: 3},
  {runner_id: 3, run_id: 25},
  {runner_id: 3, run_id: 7},
  {runner_id: 3, run_id: 15},
  {runner_id: 3, run_id: 13},
  {runner_id: 21, run_id: 18},
  {runner_id: 21, run_id: 7},
  {runner_id: 21, run_id: 28},
  {runner_id: 21, run_id: 13},
  {runner_id: 21, run_id: 1}
])
